Fiorella/Models/Expert.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Http;

namespace Fiorella.Models
{
    public class Expert
    {
        public int Id { get; set; }

        public string Image { get; set; }
        
        public string Name { get; set; }

        public string Job { get; set; }
        
        [NotMapped]
        [Required]
        public IFormFile Photo { get; set; }
    }
}

Fiorella/Areas/MyAdminPanel/Controllers/ExpertController.cs
using System;
using System.IO;
using System.Threading.Tasks;
using Fiorella.Areas.MyAdminPanel.Data;
using Fiorella.DataLayerAccess;
using Fiorella.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Fiorella.Areas.MyAdminPanel.Controllers
{
    [Area("MyAdminPanel")]
    public class ExpertController : Controller
    {
        private readonly AppDbContext _dbContext;
        private readonly IWebHostEnvironment _environment;

        public ExpertController(AppDbContext dbContext, IWebHostEnvironment environment)
        {
            _dbContext = dbContext;
            _environment = environment;
        }

        public async Task<IActionResult> Index()
        {
            var experts = await _dbContext.Experts.ToListAsync();
            return View(experts);
        }

        public async Task<IActionResult> Detail(int? id)
        {
            if (id==null)
            {
                return NotFound();
            }

            var expert = await _dbContext.Experts.FindAsync(id);
            if (expert==null)
            {
                return NotFound();
            }

            return View(expert);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( Expert expertImg)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            
            if (!expertImg.Photo.ContentType.Contains("image"))
            {
                ModelState.AddModelError("Photo","Yuklediyiniz photo olmalidir");
                return View();
            }
            if (expertImg.Photo.Length > 1024 * 1000)
            {
                ModelState.AddModelError("Photo","Yuklediyiniz photo 1 mbdan az olmalidir");
                return View();
            }

            var webRootPath = _environment.WebRootPath;
            var filename = $"{Guid.NewGuid()}-{expertImg.Photo.FileName}";
            var path = Path.Combine(webRootPath, "img", filename);

            var fileStream = new FileStream(path,FileMode.CreateNew);
            await expertImg.Photo.CopyToAsync(fileStream);

            expertImg.Image = filename;

            await _dbContext.Experts.AddAsync(expertImg); 
            await _dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id==null)
            {
                return NotFound();
            }

            var expert = await _dbContext.Experts.FindAsync(id);
            if (expert==null)
            {
                return NotFound();
            }

            return View(expert);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteExpert(int? id)
        {
            if (id==null)
            {
                return NotFound();
            }

            var expert = await _dbContext.Experts.FindAsync(id);
            if (expert==null)
            {
                return NotFound();
            }

            var path = Path.Combine(Constants.ImageFolderPath, expert.Image);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }
            
            _dbContext.Experts.Remove(expert);
            await _dbContext.SaveChangesAsync();
            
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Update(int? id)
        {
            if (id==null)
            {
                return NotFound();
            }

            var expert = await _dbContext.Experts.FindAsync(id);
            if (expert==null)
            {
                return NotFound();
            }

            return View(expert);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int? id, Expert expert)
        {
            if (id==null)
            {
                return NotFound();
            }

            if (id!=expert.Id)
            {
                return BadRequest();
            }
            var existExpert = await _dbContext.Experts.FindAsync(id);
            
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("Error","Error var");
                return View(existExpert);
            }
            if (existExpert==null)
            {
                return NotFound();
            }

            if (!expert.Photo.IsImage())
            {
                ModelState.AddModelError("Photo", "Yuklediyiniz shekil olmalidir.");
                return View(existExpert);
            }

            if (!expert.Photo.IsAllowedSize(1))
            {
                ModelState.AddModelError("Photo", "1 mb-dan az olmalidir.");
                return View(existExpert);
            }

            var path = Path.Combine(Constants.ImageFolderPath, existExpert.Image);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }

            var filename = await expert.Photo.GenerateFile(Constants.ImageFolderPath);
            existExpert.Image = filename;
            
            
            existExpert.Name = expert.Name;
            existExpert.Job = expert.Job;
            
            await _dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Fiorella/Areas/MyAdminPanel/Views/Expert/Create.cshtml
@model Expert

@{
    ViewBag.Title = "title";
    Layout = "_AdminLayout";
}
<div class="row">
    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Create Blogger</h4>
                <form class="forms-sample" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label asp-for="Name">Name</label>
                        <input class="form-control" placeholder="Name" asp-for="Name">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Job">Job</label>
                        <input class="form-control" placeholder="Job" asp-for="Job">
                        <span asp-validation-for="Job" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Photo">Photo</label>
                        <input class="form-control" placeholder="Photo" asp-for="Photo" accept="image/*">
                        <span asp-validation-for="Photo" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <a class="btn btn-light" asp-controller="Expert" asp-action="Index">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>

Fiorella/Areas/MyAdminPanel/Views/Expert/Delete.cshtml
@model Expert

@{
    ViewBag.Title = "title";
    Layout = "_AdminLayout";
}
<div class="row">
    <div class="col-lg-6">
        <div class="card mb-4 py-3 border-left-primary">
            <div class="card-body">
                <img src="~/img/@Model.Image" class="img-fluid" alt="">
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card mb-4 py-3 border-left-primary">
            <div class="card-body">
                @Model.Job
            </div>
            <div class="card-body">
                <p class="text-danger">are you sure to delete</p>
                <form method="post" class="forms-sample">
                        <button type="submit" class="btn btn-danger">Delete</button>
                </form>
                <a class="btn btn-light" asp-controller="Expert" asp-action="Index">Cancel</a>
            </div>
        </div>
    </div>
</div>

Fiorella/Areas/MyAdminPanel/Views/Expert/Detail.cshtml
@model Expert

@{
    ViewBag.Title = "title";
    Layout = "_AdminLayout";
}
<div class="row">
    <div class="col-lg-6">
        <div class="card mb-4 py-3 border-left-primary">
            <div class="card-body">
                <img src="~/img/@Model.Image" class="img-fluid" alt="">
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card mb-4 py-3 border-left-primary">
            <div class="card-body">
                @Model.Job
            </div>
        </div>
    </div>
</div>

Fiorella/Areas/MyAdminPanel/Views/Expert/Index.cshtml
@model List<Expert>

@{
    ViewBag.Title = "title";
    Layout = "_AdminLayout";
}

<h2>Experts</h2>

<div class="row">
    <div class="card-body">
        <div class="table-responsive">
            <a class="btn btn-primary" asp-controller="Expert" asp-action="Create">Create</a>
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th>Image</th>
                    <th>Expert Name</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <img src="~/img/@item.Image" style="width: 150px; height: 150px;"/>
                        </td>
                        <td>@item.Name</td>
                        <td>
                            <a class="btn btn-warning" asp-controller="Expert" asp-action="Update" asp-route-id="@item.Id">Update</a>
                            <a class="btn btn-success" asp-controller="Expert" asp-action="Detail" asp-route-id="@item.Id">Detail</a>
                            <a class="btn btn-danger" asp-controller="Expert" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>
<style>
    .img-fluid{
        max-width: 150px;
        max-height: 150px;
    }
</style>

Fiorella/Areas/MyAdminPanel/Views/Expert/Update.cshtml
@model Expert

@{
    ViewBag.Title = "title";
    Layout = "_AdminLayout";
}
<div class="row">
    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Update Blogger</h4>
                <img src="~/img/@Model.Image" style="width: 150px; height: 150px"/>
                <form class="forms-sample" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label asp-for="Name">Name</label>
                        <input class="form-control" placeholder="Name" asp-for="Name">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Job">Job</label>
                        <input class="form-control" placeholder="Job" asp-for="Job">
                        <span asp-validation-for="Job" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Photo">Photo</label>
                        <input class="form-control" placeholder="Photo" asp-for="Photo" accept="image/*">
                        <span asp-validation-for="Photo" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <a class="btn btn-light" asp-controller="Expert" asp-action="Index">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>